# Generated by Django 4.0.5 on 2022-06-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atawards', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=20),
        ),
    ]
